# Setup
title:               B3 Hapby
tagline:             '2bhapby-dev'
description:         '2bhapby-dev'
url:                 https://2bhapby.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              2bhapby
  url:               
  email:             2bhapby@gmail.com
  
  #footer
  
  footer-links:
    github: https://2bhapby.github.com
  

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
